services:
 frontend:
  container_name: frontend
  restart: always
  build: .
  volumes:
   - ./src:/usr/src/app/src
   - /usr/src/app/node_modules
  ports:
   - '5173:5173'
  healthcheck:
   test: ['CMD', 'curl', '-f', 'https://localhost:5173']
   interval: 1m30s
   timeout: 10s
   retries: 3
   start_period: 40s
