services:
 openai-connect:
  container_name: openai-connect
  restart: always
  env_file:
    - api.env
  build: .
  volumes:
   - ./src:/usr/src/app/src
   - /usr/src/app/node_modules
  ports:
   - '3000:3000'
  healthcheck:
   test: ['CMD', 'curl', '-f', 'https://localhost:3000']
   interval: 1m30s
   timeout: 10s
   retries: 3
   start_period: 40s
