name: standard checks

on:
 workflow_dispatch:
 pull_request:
  types: [opened, edited, synchronize, reopened]
 push:
  branches:
   - main

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-node@v3
     with:
      node-version: '18'
      cache: 'npm'
   - run: npm ci
   - run: npm run lint

 prettier:
  needs: lint
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-node@v3
     with:
      node-version: '18'
      cache: 'npm'
   - run: npm ci
   - run: npm run pretty

 audit:
  needs: prettier
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - uses: actions/setup-node@v3
     with:
      node-version: '18'
      cache: 'npm'
   - run: npm ci
   - run: npm audit --omit-dev
